config/routes.rb
Coconut::Application.routes.draw do
  resources :seats

  resources :flights

 match ':controller(/:action(/:id))'
 match ':controller(/:action(/:id(.:format)))'
end

app/models/flight.rb
class Flight < ActiveRecord::Base
  validates_presence_of :destination
  validates_presence_of :baggage_allowance
  validates_presence_of :capacity

  has_many :seats
end

app/models/seat.rb
class Seat < ActiveRecord::Base
  belongs_to :flight
  def validate
    if baggage > flight.baggage_allowance
      errors.add_to_base("You have too much baggage")
    end
    if flight.seats.size >= flight.capacity
      errors.add_to_base("Sorry, flight seat is over capacity")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  # GET /flights
  # GET /flights.xml
  def index
    @flights = Flight.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @flights }
    end
  end

  # GET /flights/1
  # GET /flights/1.xml
  def show
    @flight = Flight.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @flight }
    end
  end

  # GET /flights/new
  # GET /flights/new.xml
  def new
    @flight = Flight.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @flight }
    end
  end

  # GET /flights/1/edit
  def edit
    @flight = Flight.find(params[:id])
  end

  # POST /flights
  # POST /flights.xml
  def create
    @flight = Flight.new(params[:flight])

    if @flight.save
      redirect_to "/flights"
    else
      render :template => "flights/new"
    end

#    respond_to do |format|
#      if @flight.save
#        format.html { redirect_to(@flight, :notice => 'Flight was successfully created.') }
#        redirect_to "/flight/{@flight.id}"
#        format.xml  { render :xml => @flight, :status => :created, :location => @flight }
#      else
#        format.html { render :action => "new" }
#        format.xml  { render :xml => @flight.errors, :status => :unprocessable_entity }
#      end
#    end
  end

  # PUT /flights/1
  # PUT /flights/1.xml
  def update
    @flight = Flight.find(params[:id])

    respond_to do |format|
      if @flight.update_attributes(params[:flight])
        format.html { redirect_to(@flight, :notice => 'Flight was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @flight.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /flights/1
  # DELETE /flights/1.xml
  def destroy
    @flight = Flight.find(params[:id])
    @flight.destroy

    respond_to do |format|
      format.html { redirect_to(flights_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/seats_controller.rb
class SeatsController < ApplicationController
  # GET /seats
  # GET /seats.xml
  def index
    @seats = Seat.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @seats }
    end
  end

  # GET /seats/1
  # GET /seats/1.xml
  def show
    @seat = Seat.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @seat }
    end
  end

  # GET /seats/new
  # GET /seats/new.xml
  def new
    @seat = Seat.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @seat }
    end
  end

  # GET /seats/1/edit
  def edit
    @seat = Seat.find(params[:id])
  end

  # POST /seats
  # POST /seats.xml
  def create
    @seat = Seat.new(params[:seat])

    respond_to do |format|
      if @seat.save
        format.html { redirect_to(@seat, :notice => 'Seat was successfully created.') }
        format.xml  { render :xml => @seat, :status => :created, :location => @seat }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @seat.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /seats/1
  # PUT /seats/1.xml
  def update
    @seat = Seat.find(params[:id])

    respond_to do |format|
      if @seat.update_attributes(params[:seat])
        format.html { redirect_to(@seat, :notice => 'Seat was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @seat.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /seats/1
  # DELETE /seats/1.xml
  def destroy
    @seat = Seat.find(params[:id])
    @seat.destroy

    respond_to do |format|
      format.html { redirect_to(seats_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/seats_helper.rb
module SeatsHelper
end

app/views/flights/_form.html.erb
<%= form_for(@flight) do |f| %>
  <% if @flight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@flight.errors.count, "error") %> prohibited this flight from being saved:</h2>

      <ul>
      <% @flight.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :departure %><br />
    <%= f.datetime_select :departure %>
  </div>
  <div class="field">
    <%= f.label :arrival %><br />
    <%= f.datetime_select :arrival %>
  </div>
  <div class="field">
    <%= f.label :destination %><br />
    <%= f.text_field :destination %>
  </div>
  <div class="field">
    <%= f.label :baggage_allowance %><br />
    <%= f.text_field :baggage_allowance %>
  </div>
  <div class="field">
    <%= f.label :capacity %><br />
    <%= f.text_field :capacity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/flights/_new_seat.html.erb
<h1>New seat</h1>
<%= form_for(seat) do |f| %>
  <% if seat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(seat.errors.count, "error") %> prohibited this seat from being saved:</h2>

      <ul>
      <% seat.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :flight_id %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :baggage %><br />
    <%= f.text_field :baggage %>
  </div>
  <div class="actions">
    <%= f.submit "Create" %>
  </div>
<% end %>

app/views/flights/_seat_list.html.erb
<h1>Listing seats</h1>

<table>
  <tr>
    <th>Flight</th>
    <th>Name</th>
    <th>Baggage</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% seats.each do |seat| %>
  <tr>
    <td><%= seat.name %></td>
    <td><%= seat.baggage %></td>
    <td><%= link_to 'Show', seat %></td>
    <td><%= link_to 'Edit', edit_seat_path(seat) %></td>
    <td><%= link_to 'Destroy', seat, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

app/views/flights/edit.html.erb
<h1>Editing flight</h1>

<%= render 'form' %>

<%= link_to 'Show', @flight %> |
<%= link_to 'Back', flights_path %>

app/views/flights/index.html.erb
<h1>Listing flights</h1>

<table>
  <tr>
    <th>Departure</th>
    <th>Arrival</th>
    <th>Destination</th>
    <th>Baggage allowance</th>
    <th>Capacity</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @flights.each do |flight| %>
  <tr>
    <td><%= flight.departure %></td>
    <td><%= flight.arrival %></td>
    <td><%= flight.destination %></td>
    <td><%= flight.baggage_allowance %></td>
    <td><%= flight.capacity %></td>
    <td><%= link_to 'Show', flight %></td>
    <td><%= link_to 'Edit', edit_flight_path(flight) %></td>
    <td><%= link_to 'Destroy', flight, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Flight', new_flight_path %>

app/views/flights/new.html.erb
<h1>New flight</h1>

<%= render 'form' %>

<%= link_to 'Back', flights_path %>

app/views/flights/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Departure:</b>
  <%= @flight.departure %>
</p>

<p>
  <b>Arrival:</b>
  <%= @flight.arrival %>
</p>

<p>
  <b>Destination:</b>
  <%= @flight.destination %>
</p>

<p>
  <b>Baggage allowance:</b>
  <%= @flight.baggage_allowance %>
</p>

<p>
  <b>Capacity:</b>
  <%= @flight.capacity %>
</p>

<%= render :partial=>"seat_list", :locals=>{:seats=>@flight.seats} %>
<%= render :partial=>"new_seat", :locals=>{:seat=>Seat.new(:flight_id=>@flight.id)} %>


<%= link_to 'Edit', edit_flight_path(@flight) %> |
<%= link_to 'Back', flights_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Coconut</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/seats/_form.html.erb
<%= form_for(@seat) do |f| %>
  <% if @seat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@seat.errors.count, "error") %> prohibited this seat from being saved:</h2>

      <ul>
      <% @seat.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :flight_id %><br />
    <%= f.text_field :flight_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :baggage %><br />
    <%= f.text_field :baggage %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/seats/edit.html.erb
<h1>Editing seat</h1>

<%= render 'form' %>

<%= link_to 'Show', @seat %> |
<%= link_to 'Back', seats_path %>

app/views/seats/index.html.erb
<h1>Listing seats</h1>

<table>
  <tr>
    <th>Flight</th>
    <th>Name</th>
    <th>Baggage</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @seats.each do |seat| %>
  <tr>
    <td><%= seat.flight_id %></td>
    <td><%= seat.name %></td>
    <td><%= seat.baggage %></td>
    <td><%= link_to 'Show', seat %></td>
    <td><%= link_to 'Edit', edit_seat_path(seat) %></td>
    <td><%= link_to 'Destroy', seat, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Seat', new_seat_path %>

app/views/seats/new.html.erb
<h1>New seat</h1>

<%= render 'form' %>

<%= link_to 'Back', seats_path %>

app/views/seats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Flight:</b>
  <%= @seat.flight_id %>
</p>

<p>
  <b>Name:</b>
  <%= @seat.name %>
</p>

<p>
  <b>Baggage:</b>
  <%= @seat.baggage %>
</p>


<%= link_to 'Edit', edit_seat_path(@seat) %> |
<%= link_to 'Back', seats_path %>